/**
 * Full Pipeline Types
 * Story 4.7 - Pipeline Completo End-to-End
 *
 * Types and interfaces for the complete content generation pipeline
 */

/**
 * Input for the full pipeline
 */
export interface FullPipelineInput {
  /** Configuration of data sources for the Researcher agent */
  sources?: {
    devto?: boolean;
    hackernews?: boolean;
    reddit?: boolean;
  };
  /** Optional filters for trend discovery */
  filters?: {
    minEngagement?: number;
    maxAge?: number; // in hours
    keywords?: string[];
  };
}

/**
 * Options for full pipeline execution
 */
export interface FullPipelineOptions {
  /** Number of posts to generate (default: 3, max: 10) */
  numPosts?: number;
  /** Target platforms: 'instagram', 'linkedin', or 'both' (default: 'both') */
  platforms?: 'instagram' | 'linkedin' | 'both';
  /** Include visual generation - carousel and PDF (default: true) */
  includeVisual?: boolean;
  /** Minimum score threshold for approval (default: 6.0) */
  qualityThreshold?: number;
  /** Number of slides per carousel (default: 5, max: 10) */
  carouselSlides?: number;
  /** Background image style */
  backgroundStyle?: 'abstract' | 'gradient' | 'tech' | 'minimal';
}

/**
 * Default options for the full pipeline
 */
export const DEFAULT_FULL_PIPELINE_OPTIONS: Required<FullPipelineOptions> = {
  numPosts: 3,
  platforms: 'both',
  includeVisual: true,
  qualityThreshold: 6.0,
  carouselSlides: 5,
  backgroundStyle: 'tech',
};

/**
 * Output from the full pipeline
 */
export interface FullPipelineOutput {
  /** Unique execution identifier */
  executionId: string;
  /** Final status of the pipeline */
  status: 'completed' | 'partial' | 'failed';
  /** Execution summary with metrics */
  summary: ExecutionSummary;
  /** List of generated posts */
  posts: GeneratedPost[];
  /** Execution metadata */
  metadata: {
    startedAt: Date;
    completedAt: Date;
    durationMs: number;
    options: FullPipelineOptions;
  };
}

/**
 * Execution summary with metrics
 */
export interface ExecutionSummary {
  /** Total number of posts generated */
  totalGenerated: number;
  /** Posts approved by QA (score >= threshold) */
  totalApproved: number;
  /** Posts that need review (score < threshold) */
  totalNeedsReview: number;
  /** Average quality score across all posts */
  averageScore: number;
  /** Distribution of scores by category */
  scoreDistribution: {
    excellent: number;  // score >= 8.0
    good: number;       // score >= 6.0 && < 8.0
    needsWork: number;  // score < 6.0
  };
  /** Assets generated during execution */
  assetsGenerated: {
    backgrounds: number;
    carouselSlides: number;
    pdfs: number;
  };
}

/**
 * Post generated by the pipeline
 */
export interface GeneratedPost {
  /** Unique post identifier */
  id: string;
  /** Topic/theme of the post */
  topic: string;
  /** Generated text for Instagram */
  textInstagram?: string;
  /** Generated text for LinkedIn */
  textLinkedin?: string;
  /** Quality score from QA (0-10) */
  score: number;
  /** Approval status based on quality threshold */
  status: 'approved' | 'needs_review' | 'rejected';
  /** Associated visual assets */
  assets: {
    backgroundPath?: string;
    carouselPaths?: string[];
    pdfPath?: string;
  };
  /** Feedback from QA evaluation */
  qaFeedback?: string[];
}

/**
 * Execution record for database persistence
 */
export interface ExecutionRecord {
  /** Unique execution identifier */
  id: string;
  /** Current execution status */
  status: ExecutionStatus;
  /** When execution started */
  startedAt: Date;
  /** When execution completed (if finished) */
  completedAt?: Date;
  /** Pipeline configuration (JSON stringified) */
  config: string;
  /** Execution summary (JSON stringified, available after completion) */
  summary?: string;
  /** Current step being executed */
  currentStep?: string;
  /** Progress percentage (0-100) */
  progress?: number;
  /** Error message if failed */
  error?: string;
}

/**
 * Execution status enum
 */
export type ExecutionStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';

/**
 * Progress tracking for individual pipeline steps
 */
export interface PipelineStepProgress {
  /** Step name */
  step: string;
  /** Step execution status */
  status: 'pending' | 'running' | 'completed' | 'failed' | 'skipped';
  /** When step started */
  startedAt?: Date;
  /** When step completed */
  completedAt?: Date;
  /** Step duration in milliseconds */
  durationMs?: number;
  /** Step output data */
  output?: unknown;
  /** Error message if failed */
  error?: string;
}

/**
 * Filters for querying executions
 */
export interface ExecutionFilters {
  /** Filter by status */
  status?: ExecutionStatus;
  /** Filter by start date (after) */
  startedAfter?: Date;
  /** Filter by start date (before) */
  startedBefore?: Date;
  /** Limit number of results */
  limit?: number;
  /** Offset for pagination */
  offset?: number;
}

/**
 * Aggregated execution statistics
 */
export interface ExecutionStats {
  /** Total number of executions */
  total: number;
  /** Completed executions */
  completed: number;
  /** Failed executions */
  failed: number;
  /** Cancelled executions */
  cancelled: number;
  /** Average execution duration in milliseconds */
  averageDurationMs: number;
  /** Average quality score across all posts */
  averageScore: number;
  /** Total posts generated */
  totalPostsGenerated: number;
}

/**
 * Callbacks for pipeline execution progress
 */
export interface FullPipelineCallbacks {
  /** Called when a step starts */
  onStepStart?: (step: string, index: number, total: number) => void;
  /** Called when a step completes */
  onStepComplete?: (step: string, output: unknown) => void;
  /** Called when a step fails */
  onStepError?: (step: string, error: Error) => void;
  /** Called with progress updates */
  onProgress?: (progress: number, currentStep: string) => void;
  /** AbortSignal for cancellation */
  abortSignal?: AbortSignal;
}

/**
 * Configuration for the full pipeline
 */
export interface FullPipelineConfig {
  /** Pipeline identifier */
  id: string;
  /** Pipeline name */
  name: string;
  /** Pipeline description */
  description: string;
  /** Default timeout for steps in ms */
  defaultTimeout: number;
  /** Default retries per step */
  defaultRetries: number;
}

/**
 * Default configuration for the full pipeline
 */
export const DEFAULT_FULL_PIPELINE_CONFIG: FullPipelineConfig = {
  id: 'full-pipeline',
  name: 'Full Content Generation Pipeline',
  description: 'End-to-end pipeline for generating social media posts from trends',
  defaultTimeout: 60000,
  defaultRetries: 1,
};

/**
 * Step names in the full pipeline
 */
export const FULL_PIPELINE_STEPS = [
  'Pesquisador',
  'TopicGenerator',
  'Curador',
  'Writer',
  'Visual',
  'QAAnalyst',
] as const;

export type FullPipelineStepName = typeof FULL_PIPELINE_STEPS[number];
