/**
 * Visual Pipeline Types
 * Story 3.7 - Integracao Pipeline Visual
 *
 * Types and interfaces for visual content generation pipeline
 */

import type { ImageStyle } from '../../services/image-gen';

/**
 * Input for the visual pipeline
 * Supports two modes: by post_id or direct content
 */
export interface VisualPipelineInput {
  /** ID of an existing post in the database */
  postId?: string;
  /** Direct content for visual generation */
  content?: VisualPipelineContent;
}

/**
 * Direct content for visual generation
 */
export interface VisualPipelineContent {
  /** Title of the content */
  title: string;
  /** Main text content */
  text: string;
  /** Code blocks to include in carousel */
  codeBlocks?: CodeBlock[];
  /** Topic/theme for visual style */
  topic?: string;
}

/**
 * Code block for carousel slides
 */
export interface CodeBlock {
  /** Source code to display */
  code: string;
  /** Programming language for syntax highlighting */
  language: string;
}

/**
 * Options for visual pipeline generation
 */
export interface VisualPipelineOptions {
  /** Generate carousel images (default: true) */
  gerarCarousel?: boolean;
  /** Generate PDF from carousel (default: true) */
  gerarPdf?: boolean;
  /** Number of slides for carousel (default: 5, max: 10) */
  numSlides?: number;
  /** Background image style */
  backgroundStyle?: ImageStyle;
  /** Author handle for CTA slide */
  authorHandle?: string;
  /** Custom CTA text */
  ctaText?: string;
}

/**
 * Output from the visual pipeline
 */
export interface VisualPipelineOutput {
  /** Post identifier */
  postId: string;
  /** List of generated assets */
  assets: GeneratedAsset[];
  /** Generation metadata */
  metadata: VisualPipelineMetadata;
}

/**
 * Metadata for visual pipeline execution
 */
export interface VisualPipelineMetadata {
  /** Total processing time in milliseconds */
  processingTimeMs: number;
  /** When the assets were generated */
  generatedAt: Date;
  /** Options used for generation */
  options: VisualPipelineOptions;
  /** Number of steps executed */
  stepsExecuted: number;
  /** Errors that occurred during execution (if any) */
  errors?: string[];
}

/**
 * Asset generated by the visual pipeline
 */
export interface GeneratedAsset {
  /** Unique asset identifier */
  id: string;
  /** Type of asset */
  type: AssetType;
  /** Absolute path to the asset file */
  path: string;
  /** Filename only */
  filename: string;
  /** File size in bytes */
  size: number;
  /** MIME type of the file */
  mimeType: string;
  /** For carousel slides, the slide index (0-based) */
  slideIndex?: number;
  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Types of assets that can be generated
 */
export type AssetType = 'background' | 'carousel_slide' | 'pdf';

/**
 * Asset record for database storage
 */
export interface AssetRecord {
  /** Unique asset identifier */
  id: string;
  /** Post this asset belongs to */
  postId: string;
  /** Type of asset (simplified for DB) */
  type: 'image' | 'carousel' | 'pdf';
  /** Absolute path to the asset file */
  path: string;
  /** Filename only */
  filename: string;
  /** File size in bytes */
  size: number;
  /** MIME type */
  mimeType: string;
  /** When the asset was created */
  createdAt: Date;
  /** Additional metadata as JSON string */
  metadata?: string;
}

/**
 * Result of cleanup operation
 */
export interface CleanupResult {
  /** Successfully removed file paths */
  success: string[];
  /** Failed cleanup attempts */
  failed: CleanupFailure[];
}

/**
 * Details about a failed cleanup attempt
 */
export interface CleanupFailure {
  /** Path that failed to clean up */
  path: string;
  /** Error message */
  error: string;
}

/**
 * Status of the visual pipeline execution
 */
export interface VisualPipelineStatus {
  /** Pipeline execution ID */
  pipelineId: string;
  /** Current status */
  status: 'pending' | 'running' | 'completed' | 'failed';
  /** Current step being executed */
  currentStep?: string;
  /** Progress percentage (0-100) */
  progress: number;
  /** Error message if failed */
  error?: string;
  /** Started timestamp */
  startedAt: Date;
  /** Completed timestamp */
  completedAt?: Date;
}

/**
 * Configuration for the visual pipeline
 */
export interface VisualPipelineConfig {
  /** Pipeline identifier */
  id: string;
  /** Pipeline name */
  name: string;
  /** Pipeline description */
  description: string;
  /** Default timeout for steps in ms */
  defaultTimeout: number;
  /** Default retries per step */
  defaultRetries: number;
  /** Output directory for generated assets */
  outputDir: string;
  /** Default author handle */
  defaultAuthorHandle: string;
}

/**
 * Default configuration for the visual pipeline
 */
export const DEFAULT_VISUAL_PIPELINE_CONFIG: VisualPipelineConfig = {
  id: 'visual-pipeline',
  name: 'Visual Content Pipeline',
  description: 'Generates visual assets (background, carousel, PDF) for social media posts',
  defaultTimeout: 120000,
  defaultRetries: 1,
  outputDir: 'output/posts',
  defaultAuthorHandle: '@socialmedia',
};
