// Configuration types - Social Content Agent
// Environment variable names
export const ENV_VARS = {
    // Required
    GROQ_API_KEY: 'GROQ_API_KEY',
    IDEOGRAM_API_KEY: 'IDEOGRAM_API_KEY',
    // Optional
    GEMINI_API_KEY: 'GEMINI_API_KEY',
    LEONARDO_API_KEY: 'LEONARDO_API_KEY',
    PORT: 'PORT',
    NODE_ENV: 'NODE_ENV',
    LOG_LEVEL: 'LOG_LEVEL',
    DATABASE_URL: 'DATABASE_URL',
    // Sources
    DEVTO_ENABLED: 'DEVTO_ENABLED',
    HACKERNEWS_ENABLED: 'HACKERNEWS_ENABLED',
    REDDIT_ENABLED: 'REDDIT_ENABLED',
    // Quality
    QUALITY_THRESHOLD: 'QUALITY_THRESHOLD',
};
export const REQUIRED_ENV_VARS = [
    ENV_VARS.GROQ_API_KEY,
    ENV_VARS.IDEOGRAM_API_KEY,
];
export const OPTIONAL_ENV_VARS = [
    ENV_VARS.GEMINI_API_KEY,
    ENV_VARS.LEONARDO_API_KEY,
    ENV_VARS.PORT,
    ENV_VARS.NODE_ENV,
    ENV_VARS.LOG_LEVEL,
    ENV_VARS.DATABASE_URL,
    ENV_VARS.DEVTO_ENABLED,
    ENV_VARS.HACKERNEWS_ENABLED,
    ENV_VARS.REDDIT_ENABLED,
    ENV_VARS.QUALITY_THRESHOLD,
];
//# sourceMappingURL=types.js.map