/**
 * Template Engine Service
 * Story 3.3 - Templates HTML/CSS para Slides
 *
 * Provides template loading and variable interpolation for carousel slides.
 * Supports simple variable substitution, conditionals, and HTML escaping.
 */

import { readFile } from 'fs/promises';
import { join } from 'path';

/**
 * Variables supported by the template engine
 */
export interface TemplateVariables {
  /** Slide title */
  title?: string;
  /** Slide subtitle (cover slide) */
  subtitle?: string;
  /** Main content text */
  content?: string;
  /** Code snippet (raw, before highlighting) */
  code?: string;
  /** Programming language for code highlighting */
  language?: string;
  /** Highlighted code HTML (from Shiki) */
  highlightedCode?: string;
  /** Shiki theme CSS styles */
  shikiStyles?: string;
  /** Creator's handle (e.g., @username) */
  handle?: string;
  /** Call-to-action text */
  cta?: string;
  /** Background image URL */
  backgroundImage?: string;
  /** Overlay opacity (0-1) */
  overlayOpacity?: string;
  /** Overlay color (hex or rgba) */
  overlayColor?: string;
  /** Slide number (e.g., "2/5") */
  slideNumber?: string;
  /** Whether to show social icons */
  socialIcons?: boolean;
}

/**
 * Default values for template variables
 */
export const DEFAULT_TEMPLATE_VALUES: Partial<TemplateVariables> = {
  title: '',
  content: '',
  handle: '@dev',
  overlayOpacity: '0.6',
  overlayColor: 'rgba(0, 0, 0, 0.6)',
  backgroundImage: '',
  cta: 'Gostou? Salve e compartilhe!',
  language: 'typescript',
};

/**
 * HTML entities that need to be escaped to prevent XSS
 */
const HTML_ESCAPES: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

/**
 * Escapes HTML special characters to prevent XSS attacks.
 *
 * @param text - Text to escape
 * @returns Escaped text safe for HTML insertion
 *
 * @example
 * ```typescript
 * escapeHtml('<script>alert("xss")</script>')
 * // Returns: '&lt;script&gt;alert(&quot;xss&quot;)&lt;/script&gt;'
 * ```
 */
export function escapeHtml(text: string): string {
  return text.replace(/[&<>"']/g, (char) => HTML_ESCAPES[char] || char);
}

/**
 * Interpolates variables into a template string.
 *
 * Supports:
 * - Simple variables: `{{variable}}` - replaced with escaped value
 * - Conditionals: `{{#variable}}...{{/variable}}` - content shown only if variable is truthy
 * - Unescaped variables: `highlightedCode` and `shikiStyles` are NOT escaped
 *
 * @param template - Template string with variable placeholders
 * @param variables - Object with variable values
 * @returns Interpolated template string
 *
 * @example
 * ```typescript
 * const result = interpolate(
 *   '<h1>{{title}}</h1>{{#subtitle}}<p>{{subtitle}}</p>{{/subtitle}}',
 *   { title: 'Hello', subtitle: 'World' }
 * );
 * // Returns: '<h1>Hello</h1><p>World</p>'
 * ```
 */
export function interpolate(
  template: string,
  variables: TemplateVariables
): string {
  // Merge provided variables with defaults
  const merged = { ...DEFAULT_TEMPLATE_VALUES, ...variables };

  let result = template;

  // Process conditionals {{#var}}...{{/var}} recursively
  // Keep processing until no more conditionals are found (handles nested blocks)
  const conditionalRegex = /\{\{#(\w+)\}\}([\s\S]*?)\{\{\/\1\}\}/g;
  let previousResult = '';

  while (result !== previousResult) {
    previousResult = result;
    result = result.replace(conditionalRegex, (_, key, content) => {
      const value = merged[key as keyof TemplateVariables];
      // Show content only if value is truthy (not undefined, not empty string, not false)
      if (value !== undefined && value !== '' && value !== false) {
        return content;
      }
      return '';
    });
  }

  // Process simple variables {{var}}
  result = result.replace(/\{\{(\w+)\}\}/g, (_, key) => {
    const value = merged[key as keyof TemplateVariables];

    if (value === undefined || value === null) {
      return '';
    }

    // Do NOT escape HTML for highlighted code and styles
    // These contain safe HTML generated by Shiki
    if (key === 'highlightedCode' || key === 'shikiStyles') {
      return String(value);
    }

    return escapeHtml(String(value));
  });

  return result;
}

/**
 * Available template types
 */
export type TemplateType = 'cover' | 'content' | 'code' | 'cta';

/**
 * All available template types
 */
export const TEMPLATE_TYPES: TemplateType[] = ['cover', 'content', 'code', 'cta'];

/**
 * Loads a template file from disk.
 *
 * @param type - Template type to load
 * @param templatesDir - Base directory for templates (defaults to cwd/templates/carousel)
 * @returns Template HTML string
 *
 * @throws Error if template file cannot be read
 */
export async function loadTemplate(
  type: TemplateType,
  templatesDir: string = join(process.cwd(), 'templates', 'carousel')
): Promise<string> {
  const templatePath = join(templatesDir, `${type}.html`);
  const template = await readFile(templatePath, 'utf-8');
  return template;
}

/**
 * Loads and interpolates a template with the provided variables.
 *
 * @param type - Template type to render
 * @param variables - Variables to interpolate
 * @param templatesDir - Base directory for templates
 * @returns Rendered HTML string
 *
 * @example
 * ```typescript
 * const html = await renderTemplate('cover', {
 *   title: 'My Carousel',
 *   subtitle: 'Learn TypeScript',
 *   handle: '@developer'
 * });
 * ```
 */
export async function renderTemplate(
  type: TemplateType,
  variables: TemplateVariables,
  templatesDir?: string
): Promise<string> {
  const template = await loadTemplate(type, templatesDir);
  return interpolate(template, variables);
}

/**
 * Validates that a string is a valid template type.
 *
 * @param type - String to validate
 * @returns True if the string is a valid template type
 */
export function isValidTemplateType(type: string): type is TemplateType {
  return TEMPLATE_TYPES.includes(type as TemplateType);
}

/**
 * Gets all available template types.
 *
 * @returns Array of template type strings
 */
export function getTemplateTypes(): TemplateType[] {
  return [...TEMPLATE_TYPES];
}
