/**
 * QAAnalyst Visual Analysis Types
 * Story 4.3 - Agente QA Analyst - Analise de Imagens
 *
 * Types and interfaces for visual quality analysis of carousel slides
 * and images generated by the content system.
 */

import type { Asset } from '@social-content/shared';

/**
 * Types of visual issues that can be detected
 */
export enum VisualIssueType {
  /** Text/background contrast below WCAG standards */
  LOW_CONTRAST = 'low_contrast',
  /** Text is hard to read due to size/font/placement */
  POOR_READABILITY = 'poor_readability',
  /** Code formatting issues (missing highlighting, overflow) */
  CODE_FORMATTING = 'code_formatting',
  /** Visual inconsistency between carousel slides */
  INCONSISTENT_STYLE = 'inconsistent_style',
  /** Image dimensions don't meet requirements */
  WRONG_DIMENSIONS = 'wrong_dimensions',
  /** Image file is too large */
  FILE_TOO_LARGE = 'file_too_large',
  /** Image file is too small (compression artifacts) */
  FILE_TOO_SMALL = 'file_too_small',
  /** Invalid image format */
  INVALID_FORMAT = 'invalid_format',
  /** Text extends beyond visible area */
  TEXT_OVERFLOW = 'text_overflow',
  /** Code block lacks syntax highlighting */
  MISSING_SYNTAX_HIGHLIGHT = 'missing_syntax_highlight',
}

/**
 * Severity level of visual issues
 */
export enum IssueSeverity {
  /** Informational - suggestion for improvement */
  INFO = 'info',
  /** Warning - should be fixed but not critical */
  WARNING = 'warning',
  /** Error - must be fixed before publishing */
  ERROR = 'error',
}

/**
 * Feedback for a specific visual issue
 */
export interface VisualFeedback {
  /** Type of visual issue */
  type: VisualIssueType;
  /** Severity level */
  severity: IssueSeverity;
  /** Human-readable description of the problem */
  message: string;
  /** Actionable suggestion to fix the issue */
  suggestion: string;
  /** Index of the affected slide (for carousels) */
  slideIndex?: number;
  /** Affected area coordinates (optional) */
  affectedArea?: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
}

/**
 * Input for visual analysis
 */
export interface VisualAnalysisInput {
  /** Assets to analyze (images/slides) */
  assets: Asset[];
  /** Unique post identifier */
  postId: string;
  /** Whether this is a multi-slide carousel */
  isCarousel: boolean;
  /** Expected number of slides (optional) */
  expectedSlideCount?: number;
}

/**
 * Detailed visual quality score breakdown
 */
export interface VisualScore {
  /** Overall visual quality (0-10) */
  overall: number;
  /** Dimension correctness score (0-10) */
  dimensions: number;
  /** File size/format quality score (0-10) */
  fileQuality: number;
  /** Text/background contrast score (0-10) */
  contrast: number;
  /** Text readability score (0-10) */
  readability: number;
  /** Code formatting score (0-10, if applicable) */
  codeFormatting: number;
  /** Carousel slide consistency score (0-10, if applicable) */
  consistency: number;
}

/**
 * Result of carousel consistency analysis
 */
export interface SlideConsistencyResult {
  /** Whether slides are visually consistent */
  isConsistent: boolean;
  /** Consistency score (0-10) */
  score: number;
  /** Color palette match ratio (0-1) */
  colorPaletteMatch: number;
  /** Font consistency ratio (0-1) */
  fontConsistency: number;
  /** Layout consistency ratio (0-1) */
  layoutConsistency: number;
  /** Indices of slides that break consistency */
  inconsistentSlides: number[];
  /** Detailed findings */
  details: string[];
}

/**
 * Analysis result for a single slide
 */
export interface SlideAnalysisResult {
  /** Zero-based index of the slide */
  slideIndex: number;
  /** Absolute path to the image file */
  path: string;
  /** Image dimensions in pixels */
  dimensions: {
    width: number;
    height: number;
  };
  /** File size in bytes */
  fileSize: number;
  /** Image format (png, jpg, webp, etc.) */
  format: string;
  /** Whether this slide contains code */
  hasCode: boolean;
  /** WCAG contrast ratio */
  contrastRatio: number;
  /** Readability score (0-10) */
  readabilityScore: number;
  /** Issues detected on this slide */
  issues: VisualFeedback[];
}

/**
 * Complete visual analysis result
 */
export interface VisualAnalysisResult {
  /** Post identifier */
  postId: string;
  /** When the analysis was performed */
  analyzedAt: Date;
  /** Method used for analysis */
  analysisMethod: 'multimodal' | 'heuristic' | 'hybrid';
  /** Detailed score breakdown */
  score: VisualScore;
  /** Analysis results per slide */
  slides: SlideAnalysisResult[];
  /** Carousel consistency result (if carousel) */
  carouselConsistency?: SlideConsistencyResult;
  /** All feedback items */
  feedback: VisualFeedback[];
  /** Whether visual quality passed threshold */
  passed: boolean;
  /** Processing time in milliseconds */
  processingTimeMs: number;
}

/**
 * Configuration for heuristic analysis
 */
export interface HeuristicAnalysisConfig {
  /** Minimum image width in pixels */
  minWidth: number;
  /** Minimum image height in pixels */
  minHeight: number;
  /** Maximum image width in pixels */
  maxWidth: number;
  /** Maximum image height in pixels */
  maxHeight: number;
  /** Minimum file size in bytes */
  minFileSize: number;
  /** Maximum file size in bytes */
  maxFileSize: number;
  /** Allowed image formats */
  allowedFormats: string[];
  /** Minimum WCAG contrast ratio */
  minContrastRatio: number;
}

/**
 * Default heuristic analysis configuration
 */
export const DEFAULT_HEURISTIC_CONFIG: HeuristicAnalysisConfig = {
  minWidth: 1080,
  minHeight: 1080,
  maxWidth: 4096,
  maxHeight: 4096,
  minFileSize: 50000, // 50KB
  maxFileSize: 10485760, // 10MB
  allowedFormats: ['png', 'jpg', 'jpeg', 'webp'],
  minContrastRatio: 4.5, // WCAG AA standard
};

/**
 * Configuration for multimodal (LLM vision) analysis
 */
export interface MultimodalAnalysisConfig {
  /** Vision API provider */
  provider: 'gemini' | 'openai' | 'anthropic';
  /** API key for the provider */
  apiKey: string;
  /** Model identifier */
  model: string;
  /** Maximum tokens in response */
  maxTokens: number;
  /** Temperature for generation */
  temperature: number;
  /** Rate limit (requests per minute) */
  rateLimitPerMinute: number;
}

/**
 * Configuration for the QA Analyst agent visual analysis
 */
export interface QAAnalystVisualConfig {
  /** Minimum score threshold to pass (0-10) */
  threshold: number;
  /** Minimum contrast ratio for WCAG compliance */
  minContrastRatio: number;
  /** Heuristic analyzer configuration */
  heuristic?: Partial<HeuristicAnalysisConfig>;
  /** Multimodal analyzer configuration (optional) */
  multimodal?: MultimodalAnalysisConfig;
  /** Weight of visual score in overall QA (0-1) */
  visualWeight: number;
  /** Weight of text score in overall QA (0-1) */
  textWeight: number;
}

/**
 * Default QA Analyst visual configuration
 */
export const DEFAULT_QA_VISUAL_CONFIG: QAAnalystVisualConfig = {
  threshold: 6.0,
  minContrastRatio: 4.5,
  visualWeight: 0.4,
  textWeight: 0.6,
};

/**
 * Text analysis result (from existing QA)
 */
export interface TextAnalysisResult {
  /** Text quality score (0-10) */
  score: number;
  /** Score breakdown by criteria */
  criteria: Record<string, number>;
  /** Feedback items */
  feedback: string[];
}

/**
 * Combined QA result with visual and text analysis
 */
export interface QAResultWithVisuals {
  /** Post identifier */
  postId: string;
  /** Timestamp of analysis */
  timestamp: Date;
  /** Text analysis results */
  textAnalysis: TextAnalysisResult;
  /** Visual analysis results */
  visualAnalysis: VisualAnalysisResult;
  /** Weighted overall score (0-10) */
  overallScore: number;
  /** Whether post is approved */
  approved: boolean;
  /** Score threshold used */
  threshold: number;
}

/**
 * Input for QA analysis (text + visual)
 */
export interface QAInput {
  /** Post identifier */
  postId: string;
  /** Text content to analyze */
  textContent: string;
  /** Assets to analyze visually */
  assets?: Asset[];
  /** Platform-specific content */
  platformContent?: {
    instagram?: string;
    linkedin?: string;
  };
}

/**
 * Color information for contrast analysis
 */
export interface ColorInfo {
  /** Red channel (0-255) */
  r: number;
  /** Green channel (0-255) */
  g: number;
  /** Blue channel (0-255) */
  b: number;
  /** Frequency in the image */
  frequency: number;
}

/**
 * Result of contrast analysis
 */
export interface ContrastAnalysisResult {
  /** WCAG contrast ratio */
  contrastRatio: number;
  /** Dominant colors found */
  dominantColors: ColorInfo[];
  /** Passes WCAG AA (4.5:1) */
  passesWCAG_AA: boolean;
  /** Passes WCAG AAA (7:1) */
  passesWCAG_AAA: boolean;
  /** Detected issues */
  issues: VisualFeedback[];
  /** Contrast score (0-10) */
  score: number;
}

/**
 * Result of code slide analysis
 */
export interface CodeSlideAnalysisResult {
  /** Whether code was detected */
  hasCode: boolean;
  /** Whether syntax highlighting is present */
  hasSyntaxHighlighting: boolean;
  /** Detected programming language */
  language?: string;
  /** Font size assessment */
  fontSizeAdequate: boolean;
  /** Whether code overflows visible area */
  hasOverflow: boolean;
  /** Code formatting score (0-10) */
  score: number;
  /** Detected issues */
  issues: VisualFeedback[];
}

/**
 * LLM Vision API response structure
 */
export interface LLMVisionResponse {
  /** Overall quality score */
  overall_quality: number;
  /** Readability score */
  readability: number;
  /** Contrast score */
  contrast: number;
  /** Code formatting score (if applicable) */
  code_formatting?: number;
  /** Consistency score (if carousel) */
  consistency?: number;
  /** Detected issues */
  issues: Array<{
    type: string;
    severity: string;
    message: string;
    suggestion: string;
    slide_index?: number;
  }>;
  /** Summary of analysis */
  summary: string;
}
